"""Create initial tables

Revision ID: 50d1f1d3d3c3
Revises: cdf4743821da
Create Date: 2024-03-16 18:04:42.390384

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = "50d1f1d3d3c3"
down_revision: Union[str, None] = "cdf4743821da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskschedulelink", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    # ### end Alembic commands ###
