"""Initial migration

Revision ID: 90e653515401
Revises: a9e3e67a1b53
Create Date: 2024-03-16 15:57:13.020104

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = "90e653515401"
down_revision: Union[str, None] = "a9e3e67a1b53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
