"""Create initial tables

Revision ID: cdf4743821da
Revises: df15905197d6
Create Date: 2024-03-16 18:03:51.587363

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = "cdf4743821da"
down_revision: Union[str, None] = "df15905197d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskschedulelink", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    # ### end Alembic commands ###
