"""Create i

Revision ID: 4f6404972647
Revises: 13a6c6cd8510
Create Date: 2024-03-16 18:46:15.688202

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = "4f6404972647"
down_revision: Union[str, None] = "13a6c6cd8510"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskschedulelink", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_column("deadline")

    # ### end Alembic commands ###
