"""Create initial tables

Revision ID: df15905197d6
Revises: 851422dbc6b0
Create Date: 2024-03-16 17:52:55.820131

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = "df15905197d6"
down_revision: Union[str, None] = "851422dbc6b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskschedulelink", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")

    op.drop_table("schedule")
    # ### end Alembic commands ###
